AskIt--main/app/urls.py
from unicodedata import name
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index,name="index"),
    path('feed/',views.feed,name="feed"),
    path('<int:num>',views.sqd,name="sqd"),
    path('<int:q_id>/<int:ans_id>',views.display_ans,name="display_ans"),
    path('ask/',views.ask,name="ask"),
    path('add/<int:no>',views.ansadd,name="ansadd"),
    path('edit/<int:num>/<int:no>',views.editans,name="editans"),
    path('delete/<int:num>/<int:no>',views.deleteans,name="deleteans"),
    # path('reply/<int:q_id>/<int:ans_id>',views.addreply,name="addreply"),
    # path('reply_to/<int:q_id>/<int:ans_id>/<int:c_id>',views.add_reply,name="add_reply"),
    path('like_cnt/<int:id>',views.queslike,name="like"),
    path('dislike_cnt/<int:id>',views.quesdislike,name="dislike"),
    path('deleteques/<int:id>',views.deleteques,name="deleteques"),
    path('delete_comment/<int:q_id>/<int:ans_id>/<int:c_id>',views.deletecomments,name="delete_comment"),
    # path('deletereply/<int:id>/<int:no>',views.deletereply,name="deletereply"),
    path('bookmark/<int:id>',views.bookmark,name="bookmark"),
    path('profile/<int:id>',views.profile,name="profile"),
    path('moderator/<int:del_st>',views.moderator,name="moderator")
]

AskIt--main/qna/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("app.urls")),
    path('accounts/',include("allauth.urls"))
]

AskIt--main/app/forms.py
from dataclasses import fields
from django import forms
from django.forms import ModelForm
from .models import Answer,Comment
from mptt.forms import TreeNodeChoiceField

class QuestionForm(forms.Form):
    qtitle = forms.CharField(max_length=300,label='Title')


class AnswerForm(ModelForm):
    class Meta:
        model = Answer
        fields = ['ans']

class CommentForm(ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].label = ''
        self.fields['content'].label = 'Comment'
        self.fields['parent'].widget.attrs.update( 
            {'class': 'd-none'}
        )
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ['parent','content']
        widgets = {
            'content':forms.TextInput(attrs={'style':'border-radius:10px;border:2px solid black;'})
        }
            

AskIt--main/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <link
      rel="canonical"
      href="https://getbootstrap.com/docs/5.1/examples/headers/"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!-- Bootstrap core CSS -->
    <link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'CSS/feed.css' %}" />
    <script src="https://kit.fontawesome.com/58a1a16eba.js" crossorigin="anonymous"></script>
    <style>
      .question-card{
        border: 2px solid black;
        padding: 15px;
      }
    </style>
    <style>
      .oper-btn{
        background-color:white;
        border:none;
        color:blue;
        font-size: 20px;
      }
      .ans-added{
        display:none;
      }
      #id_qtitle{
        border-radius: 15px;
        border: 1.5px solid black;
        width: 40%;
        margin: 0 auto;
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      .lil {
        margin-left: 30px;
      }
      .nav-item {
        margin-left: 2em;
      }
      li:hover {
        border-bottom: 2px solid black;
      }
      .box {
        inline-size: 100%;
        white-space: nowrap;
        overflow: hidden;
      }
    </style>
    <link href="{% static 'CSS/headers.css' %}" rel="stylesheet" />
    <!-- <link href="{% static 'CSS/style1.css' %}" rel="stylesheet" /> -->
</head>
<body>
    <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'ask' %}">Ask</a>
              </li>
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav> -->
      <div class="container">
        <header class="p-3 bg-white text-black">
          <div class="container">
            <div
              class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
            >
              <a
                href="/"
                class="d-flex align-items-center mb-2 mb-lg-0 text-black text-decoration-none"
              >
                <h1>ASK IT!</h1>
              </a>

              <ul
                class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
              >
                <li>
                  <a href="/" class="nav-link px-2 text-black"
                    >Home</a
                  >
                </li>
                <!-- <li>
                  <a href="#" class="nav-link px-2 text-black">Features</a>
                </li> -->
                <li>
                  <a href="{% url 'feed' %}" class="nav-link px-2 text-black"
                    >Feed</a
                  >
                </li>

                
              </ul>
              <!-- {% if q %}
              <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'feed' %}">
                <input
                  type="search"
                  class="form-control form-control-grey"
                  placeholder="Search..."
                  aria-label="Search"
                  name="q"
                  value="{{q}}"
                />
              </form>
              {% else %}  
              <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" action="{% url 'feed' %}">
                <input
                  type="search"
                  class="form-control form-control-grey"
                  placeholder="Search..."
                  aria-label="Search"
                  name="q"
                />
              </form>
              {% endif %} -->
              {% if request.user.is_authenticated %}
              {% else %}
              <div class="text-end">
                <button type="button" class="btn btn-outline-dark btn- me-2">
                  <a href="{% url 'account_login' %}">Login</a>
                </button>
                <button
                  type="button"
                  class="btn btn-warning"
                  style="text-decoration: none"
                >
                  <a href="{% url 'account_signup' %}">Sign-up</a></button
                >&emsp;&emsp;
              </div>
              {% endif %}
              
              <!-- <div class="dropdown text-end">
                <a
                  href="sign-up.html"
                  class="d-block link-dark text-decoration-none dropdown-toggle"
                  id="dropdownUser1"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  profile
                </a>
              </div> -->
              {% if request.user.is_authenticated %}
              <div class="dropdown">
                <button class="dropbtn"><i class="fas fa-user"></i></button>
                <div class="dropdown-content">
                  <a href="{% url 'profile' request.user.id %}">Profile</a>
                  <a href="{% url 'account_logout' %}">Logout </a>
                  {% if request.user.is_superuser %}
                  <a href="{% url 'moderator' 0 %}">Moderator</a>
                  {% endif %}
                </div>
              </div>
              {% endif %}
            </div>
          </div>
        </header>
      </div>
    {% block body %}
    {% endblock %}
    <div class="container">
      <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
          <li class="nav-item">
            <a href="{% url 'index' %}" class="nav-link px-2 text-muted">Home</a>
          </li>
          <li class="nav-item">
            <a href="{% url 'feed' %}" class="nav-link px-2 text-muted">Feed</a>
          </li>
          
        </ul>
        <p class="text-center text-muted">&copy; 2021 Company, Inc</p>
      </footer>
    </div>
    <script>
      function showans(){
        const ansbtn = document.querySelector('.ans-added');
        if(ansbtn.style.display == 'block'){
          ansbtn.style.display = 'none';
        }else{
          ansbtn.style.display = 'block';
        }
      }
      const all = document.querySelectorAll('.form--title');
      const whole = document.querySelectorAll('.form12') 
      const title = document.querySelector('#id_qtitle');
      title.onkeyup = ()=>{
        const str = title.value.toUpperCase();
        for(let i=0; i<all.length; i++){
        let s1 = all[i].getElementsByTagName("a")[0];
        s1 = s1.textContent || s1.innerText;
        if(s1.toUpperCase().indexOf(str) > -1){
          whole[i].style.display = "";
        }else{
          whole[i].style.display = "none";
        }
      }
      }
    </script>
    <script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.js"></script>
</body>
</html>

AskIt--main/templates/messages.html
<!-- {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
{% endif %} -->
{% if messages %}
    {% for message in messages %}
        <div class="alert {{message.tags}}" id="djmsg" role="alert">
            {{message}}
        </div>
    {% endfor %}
{% endif %}